_BASE_ : ./logger/logger_hook.yaml

hook:
  name:
    - OptimizerHook
    - SchedulerHook
    - CheckpointHook
    - ModelHook
  OptimizerHook:
    priority: LOW
    interval: 1
  CheckpointHook:
    priority: NORMAL
    interval: 1
    out_dir:
    save_meta: False
    save_optimizer: True
  SchedulerHook:
    priority: VERY_LOW
    mode: default
    interval: 1
  ModelHook:
    priority: LOWEST
