_BASE_: ./logger/logger_hook.yaml
HOOK:
  NAME:
    - OptimizerHook
    - SchedulerHook
    - CheckpointHook

  OptimizerHook:
    priority: HIGH
    interval: 1

  CheckpointHook:
    priority: NORMAL
    interval: -1
    out_dir:
    save_meta: False
    save_optimizer: True

  SchedulerHook:
    priority: LOWEST
    mode: 'default'
    interval: 1