logger_hook:
  name:
    - LossLoggerHook
    - TensorboardLoggerHook
    - TextLoggerHook
  LossLoggerHook:
    priority: VERY_HIGH
  TensorboardLoggerHook:
    priority: HIGH
    interval: 1
  TextLoggerHook:
    priority: HIGH
    interval: 500
